"""Project constants."""

from __future__ import annotations

from enum import StrEnum


class UserRole(StrEnum):
    USER = "user"
    ADMIN = "admin"


class ErrorCode:
    SUCCESS = 0
    PARAMS_ERROR = 40000
    NOT_LOGIN_ERROR = 40100
    NO_AUTH_ERROR = 40101
    FORBIDDEN_ERROR = 40300
    NOT_FOUND_ERROR = 40400
    TOO_MANY_REQUEST = 42900
    SYSTEM_ERROR = 50000
    OPERATION_ERROR = 50001


ERROR_MESSAGE_MAP: dict[int, str] = {
    ErrorCode.SUCCESS: "ok",
    ErrorCode.PARAMS_ERROR: "请求参数错误",
    ErrorCode.NOT_LOGIN_ERROR: "未登录",
    ErrorCode.NO_AUTH_ERROR: "无权限",
    ErrorCode.FORBIDDEN_ERROR: "禁止访问",
    ErrorCode.NOT_FOUND_ERROR: "请求数据不存在",
    ErrorCode.TOO_MANY_REQUEST: "请求过于频繁",
    ErrorCode.SYSTEM_ERROR: "系统内部异常",
    ErrorCode.OPERATION_ERROR: "操作失败",
}

USER_LOGIN_STATE = "user_login"
SESSION_COOKIE_NAME = "SESSION"
SESSION_KEY_PREFIX = "session:"
SESSION_EXPIRE_SECONDS = 30 * 24 * 60 * 60
PASSWORD_SALT = "yupi"
DEFAULT_USER_NAME = "无名"
DEFAULT_USER_PASSWORD = "12345678"
DEFAULT_PAGE_NUM = 1
DEFAULT_PAGE_SIZE = 10
MAX_PAGE_SIZE = 100

API_KEY_PREFIX = "sk-"
API_KEY_STATUS_ACTIVE = "active"
API_KEY_STATUS_REVOKED = "revoked"
REQUEST_STATUS_SUCCESS = "success"
REQUEST_STATUS_FAILED = "failed"
CHAT_OBJECT = "chat.completion"
DEFAULT_LOG_LIMIT = 100
MODEL_TYPE_CHAT = "chat"
MODEL_STATUS_ACTIVE = "active"
MODEL_STATUS_INACTIVE = "inactive"
MODEL_STATUS_DEPRECATED = "deprecated"
PROVIDER_STATUS_ACTIVE = "active"
PROVIDER_STATUS_INACTIVE = "inactive"
PROVIDER_STATUS_MAINTENANCE = "maintenance"
HEALTH_STATUS_HEALTHY = "healthy"
HEALTH_STATUS_UNHEALTHY = "unhealthy"
HEALTH_STATUS_DEGRADED = "degraded"
HEALTH_STATUS_UNKNOWN = "unknown"
ROUTING_STRATEGY_AUTO = "auto"
ROUTING_STRATEGY_COST_FIRST = "cost_first"
ROUTING_STRATEGY_LATENCY_FIRST = "latency_first"
ROUTING_STRATEGY_ROUND_ROBIN = "round_robin"
ROUTING_STRATEGY_FIXED = "fixed"
MAX_FALLBACK_RETRIES = 3
HEALTH_CHECK_INTERVAL_SECONDS = 30
HEALTH_CHECK_TIMEOUT_MS = 10000
HEALTH_CHECK_STATS_HOURS = 24
HEALTH_CHECK_MAX_HISTORY_SIZE = 100
SCORE_COST_WEIGHT = 0.3
SCORE_LATENCY_WEIGHT = 0.3
SCORE_SUCCESS_RATE_WEIGHT = 0.2
SCORE_PRIORITY_WEIGHT = 0.2
